### ISSUE TITLE
Endgame "issues"

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#5] opened 2024-02-17 21:09 UTC
IIRC endgame is not fully discussed yet, but:
- sa-x doesnt currently spawn in operations deck
- omega only makes sa-x spawn if you manually get down to low health. its claw swipe will not insta-put you into low health
- you can warp to start during countdown, which makes countdown still count down, and the broken hangar event never being set.

**Comment by AntyMew** [comment] 2024-02-18 03:23
Unimplemented currently. SA-X will spawn only when go mode conditions are met, which haven't been decided yet. Omega Metroid is broken because the boss checks for the orange suit, which is not yet granted

The warp to ship bug is a separate issue, unrelated to endgame events. Warp to ship manually reloads the save file, everything but the countdown persisting is expected behavior

**Comment by AntyMew** [comment] 2024-02-19 02:47
Correction: Omega Metroid was checking for ice, not the orange suit. This is resolved with ef2149d

**Comment by AntyMew** [comment] 2024-03-05 04:12
Closing. SA-X should now spawn after finding a configurable amount of infant metroids

**Closed by AntyMew** 2024-03-05 04:12 UTC
